grammar org.xtext.example.mydsl.MyDsl with org.eclipse.xtext.common.Terminals

generate myDsl "http://www.xtext.org/example/mydsl/MyDsl"

Model:
	(rules+=Rule)+;

Rule:
	"<" name=ID ">" "::=" expression=Expression;

Expression:
	elements+=Element ("|" elements+=Element)*;

Element:
	(terms+=Term)+;

Term:
	kConstr+=KeyConstr | rCall+=RuleCall;

KeyConstr:
	kword+=Keyword (".." kword+=Keyword)?;

Keyword:
	text=STRING;

RuleCall:
	"<" ref=[Rule|ID] ">";

