/*
 * generated by Xtext
 */
package net.unicoen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class UniMapperGeneratorUiModule extends net.unicoen.ui.AbstractUniMapperGeneratorUiModule {
	public UniMapperGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
