/*
 * generated by Xtext
 */
package net.unicoen.testcasegenerator.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TestCaseGeneratorUiModule extends net.unicoen.testcasegenerator.ui.AbstractTestCaseGeneratorUiModule {
	public TestCaseGeneratorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
