/*
 * generated by Xtext
 */
package net.unicoen;

import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class UniMapperGeneratorRuntimeModule extends net.unicoen.AbstractUniMapperGeneratorRuntimeModule {
	@Override
	public Class<? extends IValueConverterService> bindIValueConverterService() {
		return MyTerminalConverters.class;
	}
}
