/*
 * generated by Xtext
 */
package net.unicoen;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class UniMapperGeneratorRuntimeModule extends net.unicoen.AbstractUniMapperGeneratorRuntimeModule {

}
