/*
 * generated by Xtext
 */
package com.waseda.enixer.exbnf.validation

import org.eclipse.xtext.validation.Check
import com.waseda.enixer.exbnf.exBNF.Grammar
import com.waseda.enixer.exbnf.exBNF.ExBNFPackage

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class ExBNFValidator extends AbstractExBNFValidator {

	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkGreetingStartsWithCapital(Grammar greeting) {
		if (!Character.isUpperCase(greeting.name.charAt(0))) {
			warning('Name should start with a capital', greeting, ExBNFPackage.Literals.GRAMMAR__PREQUELS, INVALID_NAME)
		}
	}
}
