/*
* generated by Xtext
*/
package net.unicoen.testcasegenerator;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestCaseGeneratorStandaloneSetup extends TestCaseGeneratorStandaloneSetupGenerated{

	public static void doSetup() {
		new TestCaseGeneratorStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

