/*
 * generated by Xtext
 */
package net.unicoen.testcasegenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TestCaseGeneratorRuntimeModule extends net.unicoen.testcasegenerator.AbstractTestCaseGeneratorRuntimeModule {

}
