/*
 * generated by Xtext
 */
package com.waseda.enixer.exbnf.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ExBNFUiModule extends com.waseda.enixer.exbnf.ui.AbstractExBNFUiModule {
	public ExBNFUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
