/*
 * generated by Xtext
 */
package net.unicoen.testcasegenerator.ui.contentassist

import net.unicoen.testcasegenerator.ui.contentassist.AbstractTestCaseGeneratorProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class TestCaseGeneratorProposalProvider extends AbstractTestCaseGeneratorProposalProvider {
}
