/*
 * generated by Xtext
 */
package com.waseda.enixer.exbnf.ui.contentassist

import com.waseda.enixer.exbnf.ui.contentassist.AbstractExBNFProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class ExBNFProposalProvider extends AbstractExBNFProposalProvider {
}
