/*
 * generated by Xtext
 */
package com.waseda.enixer.exbnf;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ExBNFRuntimeModule extends com.waseda.enixer.exbnf.AbstractExBNFRuntimeModule {

}
